// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonSchemaGenerator
{
    internal sealed partial class Vsix
    {
        public const string Id = "JsonSchemaGenerator.dbd91e6f-6362-4949-9b6c-c2d190ade159";
        public const string Name = "JSON Schema Tools";
        public const string Description = @"Allows you to easily generate a schema file from a JSON file and generate a JSON file with dummy data based on a schema file.";
        public const string Language = "en-US";
        public const string Version = "1.0.505";
        public const string Author = "Mads Kristensen";
        public const string Tags = "json, schema";
    }
}
