// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JsonSchemaGenerator
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string JsonFileString = "9955383a-5cc6-4936-998b-df9ac0a61916";
        public static Guid JsonFile = new Guid(JsonFileString);

        public const string JsonSchemaGeneratorString = "9955383a-5cc6-4936-998b-df9ac0a61915";
        public static Guid JsonSchemaGenerator = new Guid(JsonSchemaGeneratorString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int FlyoutMenuGroup = 0x0002;
        public const int FlyoutMenu = 0x0003;
        public const int GenerateSchema = 0x0100;
        public const int GenerateSample = 0x0110;
    }
}
